package com.deepseekharness.app.util;

/**
 * 界面文案统一入口。当前阶段（阶段5 之前）直接返回中文原文；
 * 多语言改造时在此扩展 values-en / LanguageController。
 */
public final class UiText {
    private static volatile String language = "zh";
    private UiText() { }
    public static void setLanguage(String value) {
        language = com.deepseekharness.app.util.UiLanguagePreference.normalize(value);
    }
    public static String language() { return language; }
    /** 当前界面文案：zh 直出中文；en 时按词表返回英文（未收录词条回退中文）。 */
    public static String text(String zh) {
        if (!"en".equals(language)) return zh;
        String english = EN.get(zh);
        return english != null ? english : zh;
    }
    private static final java.util.Map<String, String> EN = new java.util.LinkedHashMap<>();
    static {
        EN.put("设置", "Settings");
        EN.put("保存", "Save");
        EN.put("取消", "Cancel");
        EN.put("关闭", "Close");
        EN.put("知道了", "Got it");
        EN.put("确定", "OK");
        EN.put("确认", "Confirm");
        EN.put("安装", "Install");
        EN.put("配置", "Configure");
        EN.put("关于", "About");
        EN.put("更新", "Update");
        EN.put("搜索", "Search");
        EN.put("正在检测…", "Checking…");
        EN.put("重启 Web", "Restart Web");
        EN.put("开始", "Start");
        EN.put("停止", "Stop");
        EN.put("进入", "Enter");
        EN.put("进入对话", "Open chat");
        EN.put("插件", "Plugins");
        EN.put("插件管理", "Manage plugins");
        EN.put("终端", "Terminal");
        EN.put("简易终端", "Simple terminal");
        EN.put("等待鉴权链接…", "Waiting for auth link…");
        EN.put("正在读取插件…", "Loading plugins…");
        EN.put("没有符合条件的插件", "No matching plugins");
        EN.put("系统诊断", "Diagnostics");
        EN.put("在线更新", "Online update");
        EN.put("检测修复", "Install & Repair");
        EN.put("功能设置", "Settings");
        EN.put("备份还原", "Backup & Restore");
        EN.put("权限配置", "Permissions");
        EN.put("系统修复", "System Repair");
        EN.put("数据与备份", "Backup & Restore");
        EN.put("设备能力授权", "Device Permissions");
        EN.put("在线安装", "Online Install");
        EN.put("命令行安装", "Command Install");
        EN.put("名称 A-Z", "Name A-Z");
        EN.put("名称 Z-A", "Name Z-A");
        EN.put("已启用优先", "Enabled first");
        EN.put("同步本机安装状态", "Sync status");
        EN.put("名称排序", "Sort");
        EN.put("名称 A-Z", "A-Z");
        EN.put("名称 Z-A", "Z-A");
        EN.put("已启用优先", "Enabled first");
        EN.put("可更新优先", "Updates first");
        EN.put("插件列表", "Plugins");
        EN.put("模块", "Modules");
        EN.put("其他", "More");
        EN.put("当前：", "Current: ");
        EN.put("接口、行为与权限", "Interface, behavior & permissions");
        EN.put("安装与修复运行环境", "Install & repair the runtime");
        EN.put("备份恢复 · 文件共享", "Backup & restore · file sharing");
        EN.put("权限", "permissions");
        EN.put("从 GitHub Releases 获取最新版本", "Get the latest release from GitHub");
        EN.put("下载错误日志 · 环境检查 · 故障修复", "Logs · environment check · repair");
        EN.put("dsh / npm 损坏时用；配置与对话记录会保留", "For broken dsh / npm; keeps config & chats");
        EN.put("镜像与源", "Mirrors & Sources");
        EN.put("镜像切换", "switch");
        EN.put("界面语言", "Language");
        EN.put("关于软件", "About");
        EN.put("免费声明 · 交流群 · 开发者", "Free · community · developer");
        EN.put("正在关闭此终端…", "Closing this terminal…");
        EN.put("切换到终端 ", "Switch to terminal ");
        EN.put("终端 ", "Terminal ");
        EN.put(" · 关闭中…", " · closing…");
        EN.put("会话已强制结束", "Session force-stopped");
        EN.put("DeepSeek Harness 安卓启动器\n", "DeepSeek Harness Android launcher\n");
        EN.put("🌟 GitHub：", "🌟 GitHub: ");
        EN.put("🐧 QQ 交流群：", "🐧 QQ group: ");
        EN.put("QQ 群", "QQ group");
        EN.put("打不开，请手动访问：", "Cannot open; visit manually: ");
        EN.put("打不开 QQ，请手动搜索群号：", "Cannot open QQ; search the group number manually: ");
        EN.put("正在处理，请等待结果…", "Processing, please wait…");
        EN.put("开始配对", "Start pairing");
        EN.put("无线 ADB 需要局域网权限，以发现配对端口并连接设备", "Wireless ADB needs local-network permission to discover the pairing port and connect");
        EN.put("局域网权限已允许，请输入本次配对码后开始配对", "Local-network permission granted; enter this pairing code to start");
        EN.put("未允许局域网访问，请在系统 DeepSeek Harness 权限设置中允许后重试", "Local-network access not allowed; enable it in the system DeepSeekHarness permission settings and retry");
        EN.put("ADB 无线配对", "ADB Wireless Pairing");
        EN.put("系统设置 → 开发者选项 → 无线调试 → 使用配对码配对设备。\n", "System Settings → Developer options → Wireless debugging → Pair device with pairing code.\n");
        EN.put("输入本次的 6 位码，每次配对都会重新发现本机端口。首次准备环境可能较久，码过期后请重新获取。\n", "Enter the 6-digit code shown. The local port is rediscovered on every pairing. First-time environment setup may take a while; if the code expires, fetch a new one.\n");
        EN.put("配对端口与无线调试主页面的连接端口不同；已配对时可直接验证连接。", "The pairing port differs from the connect port on the main Wireless debugging page; if already paired, verify the connection directly.");
        EN.put("6 位配对码", "6-digit pairing code");
        EN.put("验证已有连接", "Verify existing connection");
        EN.put("自动读取本次配对码", "Auto-read pairing code");
        EN.put("打开无线调试设置", "Open wireless debugging settings");
        EN.put("手动地址与端口", "Manual address & port");
        EN.put("需要先开启无障碍服务", "Accessibility service required");
        EN.put("开启后请返回这里，再点自动读取。仅在你发起后的两分钟内读取系统配对弹窗；配对码不保存、不上传。", "After enabling, return here and tap auto-read. The pairing popup is read only within two minutes after you start; codes are never saved or uploaded.");
        EN.put("去开启", "Enable now");
        EN.put("无法打开无障碍设置，请手动进入系统设置开启", "Cannot open accessibility settings; enable it manually in system settings");
        EN.put("请手动进入开发者选项 → 无线调试 → 使用配对码配对设备", "Open Developer options → Wireless debugging → Pair device with pairing code manually");
        EN.put("本机 IP（可留空自动选择）", "Device IP (leave empty to auto-pick)");
        EN.put("配对弹窗端口（留空重新发现）", "Pairing popup port (empty to rediscover)");
        EN.put("主页面连接端口（留空重新发现）", "Main connect port (empty to rediscover)");
        EN.put("请填写本机无线调试页面的 IP", "Enter the IP shown on the device's wireless debugging page");
        EN.put("手动设置已保存。配对端口只用于下一次尝试，之后重新发现；可留空恢复自动发现。", "Manual settings saved. The pairing port is used only for the next attempt and then rediscovered; leave empty to restore auto-discovery.");
        EN.put("输入配对码后开始；端口会重新发现。", "Enter the pairing code to start; the port is rediscovered.");
        EN.put("配对任务被系统中断，结果尚不确定。请先验证已有连接；若仍未配对，再获取新配对码。", "The pairing task was interrupted by the system; the result is uncertain. Verify the existing connection first; if not paired, fetch a new code.");
        EN.put("请输入本次配对码", "Enter the current pairing code");
        EN.put("已开始监听，两分钟内有效。请打开系统的「使用配对码配对设备」弹窗。", "Listening started; valid for two minutes. Open the system “Pair device with pairing code” popup.");
        EN.put("自动读码已到期；请重新点自动读取，或手动输入本次配对码。", "Auto-read expired; tap auto-read again or enter the code manually.");
        EN.put("无线调试已关闭，请先开启", "Wireless debugging is off; enable it first");
        EN.put("配对码必须恰好为 6 位数字", "The pairing code must be exactly 6 digits");
        EN.put("局域网权限未允许，请先在 DeepSeek Harness 权限设置中允许", "Local-network permission not granted; allow it in the DeepSeek Harness permission settings first");
        EN.put("正在准备已有连接验证…", "Preparing existing-connection verification…");
        EN.put("正在准备配对环境…", "Preparing the pairing environment…");
        EN.put("ADB 验证完整任务", "Full ADB verification task");
        EN.put("ADB 配对完整任务", "Full ADB pairing task");
        EN.put("ADB 操作未完成：", "ADB operation incomplete: ");
        EN.put("ADB 操作已取消", "ADB operation cancelled");
        EN.put("环境未就绪，请先完成环境安装", "Environment not ready; finish the environment install first");
        EN.put("正在重新发现本机配对端口（最多 6 秒）…", "Rediscovering the pairing port (up to 6 s)…");
        EN.put("正在验证已配对的设备连接，最多约 1 分钟…", "Verifying the paired device connection, up to ~1 minute…");
        EN.put("正在完成一次配对握手并验证连接，最多约 2 分钟；随后检查自动恢复授权…", "Completing one pairing handshake and verifying the connection, up to ~2 minutes; then checking auto-recovery authorization…");
        EN.put("连接已验证，ADB 设备命令可用。\n\n", "Connection verified; ADB device commands are available.\n\n");
        EN.put("配对已完成，连接尚未验证。请检查连接端口后点「验证已有连接」，无需再次配对。\n\n", "Pairing complete, but the connection is not verified yet. Check the connect port and tap “Verify existing connection” — no need to pair again.\n\n");
        EN.put("连接验证未通过。\n\n", "Connection verification failed.\n\n");
        EN.put("配对未完成，请按以下原因处理。\n\n", "Pairing incomplete; address the reasons below.\n\n");
        EN.put("保存配置", "Saving configuration");
        EN.put("正在", "Currently ");
        EN.put("，完成后再保存配置", "; save the configuration once it's done");
        EN.put("密钥加密保存失败，原配置已保留，请重试", "Failed to save the encrypted key; the previous configuration is kept, please retry");
        EN.put("已保存；网页显示选项重新进入对话生效，端口与运行时需重启 Web", "Saved; web display options apply on the next chat session, port & runtime need a Web restart");
        EN.put("配置保存未完成：", "Configuration save incomplete: ");
        EN.put("未取得悬浮窗权限，请到系统设置 → 应用 → DeepSeek Harness → 悬浮窗中允许", "No overlay permission; allow it under System Settings → Apps → DeepSeek Harness → Display over other apps");
        EN.put("无法打开浏览器", "Cannot open the browser");
        EN.put("底色", "Background");
        EN.put("底色不透明度", "Background opacity");
        EN.put("最多显示几行（写满后丢最旧一行）", "Max lines shown (oldest line dropped when full)");
        EN.put(" 行", " lines");
        EN.put("字号（越小一行放得越多）", "Font size (smaller fits more per line)");
        EN.put("无新内容后停留", "Hold after no new output");
        EN.put(" 秒", " s");
        EN.put("显示思考过程（reasoning，会明显更吵）", "Show reasoning output (much noisier)");
        EN.put("工具调用带上命令原文（否则只看到「正在执行命令」）", "Include the raw command in tool calls (otherwise only “Running command” is shown)");
        EN.put("危险命令在悬浮条上直接批准（不必切回 App 或拉通知栏）", "Approve dangerous commands directly on the overlay (no need to return to the app or the notification shade)");
        EN.put("悬浮条外观与行为", "Overlay look & behavior");
        EN.put("预览", "Preview");
        EN.put("已保存（下一条输出即生效）", "Saved (applies from the next output)");
        EN.put("还没给悬浮窗权限，先勾上面那个开关授权", "Overlay permission not granted yet; enable the switch above to authorize it first");
        EN.put("这是预览：AI 的回复会像这样流出来，调工具时会变成", "This is a preview: AI replies stream out like this, and become ");
        EN.put("「⚙ 正在执行命令: ls -la」这种。", "“⚙ Running command: ls -la” and so on.");
        EN.put("：", ": ");
        EN.put("请先启用「允许 Root Shell」", "Enable “Allow Root Shell” first");
        EN.put("未找到 su；请确认手机已 root，且 root 管理器允许本应用使用", "su not found; confirm the phone is rooted and the root manager allows this app");
        EN.put("当前系统没有配对码接口", "This system has no pairing-code API");
        EN.put("无线调试配对码需要 Android 11+。Android 6—10 可使用 Shizuku、已授权的 root，或由电脑开启 ADB TCP 通道。", "Wireless-debugging pairing codes require Android 11+. On Android 6–10 use Shizuku, granted root, or enable the ADB TCP channel from a computer.");
        EN.put("持续允许读取短信？", "Keep allowing SMS access?");
        EN.put("当前 DSHA 环境内的助手和插件将能通过已授权的 root 或 ADB 查询短信，包括正文、号码和可能存在的验证码。\n\n后续短信查询不再逐条询问。可随时回到本页关闭，恢复逐次确认。", "Assistants and plugins inside the DSHA environment will be able to query SMS via granted root or ADB, including body text, numbers and possible verification codes.\n\nLater SMS queries won't ask again. Return here anytime to turn it off and restore per-query confirmation.");
        EN.put("允许短信读取", "Allow SMS access");
        EN.put("未检测到 Stellar 服务", "Stellar service not detected");
        EN.put("请先安装 Stellar 管理器（https://github.com/roro2239/Stellar/releases），启动服务后回到这里授权。", "Install the Stellar manager first (https://github.com/roro2239/Stellar/releases), start the service, then come back here to authorize.");
        EN.put("Stellar 已授权", "Stellar authorized");
        EN.put("正在验证 Stellar 通道…", "Verifying the Stellar channel…");
        EN.put("Stellar 通道已验证", "Stellar channel verified");
        EN.put("验证失败，请重新授权", "Verification failed; re-authorize");
        EN.put("设置保存失败，请重试", "Failed to save settings; please retry");
        EN.put("授权保存失败，请重试", "Failed to save the authorization; please retry");
        EN.put("短信查询已预授权", "SMS queries pre-authorized");
        EN.put("已撤销，后续查询需逐次确认", "Revoked; future queries need per-query confirmation");
        EN.put("已预授权 · 关闭可撤销", "Pre-authorized · toggle off to revoke");
        EN.put("未预授权 · 每次查询需确认", "Not pre-authorized · each query asks");
        EN.put("Stellar 未运行。安装 Stellar 管理器并启动服务后，点「授权 Stellar」激活（激活后设备命令走 Stellar，免 ADB）。", "Stellar is not running. Install the Stellar manager, start the service, then tap “Authorize Stellar” (device commands then go through Stellar — no ADB needed).");
        EN.put("Stellar 服务已运行，尚未授权 → 点「授权 Stellar」弹出授权即可。", "Stellar is running but not authorized → tap “Authorize Stellar” to pop up the grant.");
        EN.put("Stellar 已授权，正在连接服务…（稍后自动就绪）", "Stellar authorized; connecting to the service… (ready shortly)");
        EN.put("Stellar 已激活 ✓ 设备命令走 Stellar（shell 权限），无需 ADB 配对。", "Stellar active ✓ device commands go through Stellar (shell permission) — no ADB pairing needed.");
        EN.put("Stellar 状态读取失败：", "Failed to read Stellar status: ");
        EN.put("设备命令保护始终生效；", "Device-command protection is always on; ");
        EN.put("正在验证设备通道…", "Verifying the device channel…");
        EN.put("设备通道验证", "Device channel verification");
        EN.put("尚未安装 Shizuku，请安装后启动服务", "Shizuku is not installed; install it and start the service");
        EN.put("无法打开 Shizuku：", "Cannot open Shizuku: ");
        EN.put("验证 Shizuku 连接", "Verify Shizuku connection");
        EN.put("授权 Shizuku", "Authorize Shizuku");
        EN.put("环境任务进行中", "Environment task in progress");
        EN.put("ADB 已关闭。开启并保存后才会保持连接。", "ADB is off. It stays connected only after you enable and save it.");
        EN.put("环境任务进行中，ADB 暂停检查，完成后自动重试。", "Environment task in progress; ADB checks are paused and retry automatically when done.");
        EN.put("等待无线配对：需要在系统设置使用配对码（设备若重启，配对可能失效需要重连）", "Waiting for wireless pairing: use a pairing code in system settings (pairing may be lost and need re-pairing after a device restart)");
        EN.put("已连接 ADB（127.0.0.1:", "ADB connected (127.0.0.1:");
        EN.put("）。自动重连服务保持连接，重启后会自动恢复。", "). The auto-reconnect service keeps it alive and restores it after reboot.");
        EN.put("ADB 已开启，尚未连接。点「ADB 无线配对」完成配对。", "ADB enabled but not connected. Tap “ADB Wireless Pairing” to complete pairing.");
        EN.put("ADB 状态读取失败：", "Failed to read ADB status: ");
        EN.put("无法打开电池优化设置", "Cannot open battery-optimization settings");
        EN.put("打开设置失败：", "Failed to open settings: ");
        EN.put("存储权限已授予，容器可访问手机存储", "Storage permission granted; the container can access device storage");
        EN.put("当前系统无需存储权限", "This system needs no storage permission");
        EN.put("已开启：容器可读写手机存储任意文件", "Enabled: the container can read/write any file on device storage");
        EN.put("未开启：仅能访问 App 私有目录；去系统设置开启后可访问全部文件", "Disabled: only the app's private directory is accessible; enable in system settings for full file access");
        EN.put("打不开无障碍设置：", "Cannot open accessibility settings: ");
        EN.put("✅ 已开启：AI 可读屏 / 点按 / 输入 / 截屏", "✅ Enabled: AI can read the screen / tap / type / screenshot");
        EN.put("❌ 未开启：点上方到系统设置开启「DeepSeek Harness 配对助手」", "❌ Disabled: tap above to enable “DeepSeek Harness Assistant” in system settings");
        EN.put("⚠️ 状态未知：点上方到系统设置确认已开启", "⚠️ Unknown: tap above to confirm it's enabled in system settings");
        EN.put("无法写入所选位置", "Cannot write to the selected location");
        EN.put("诊断报告已导出", "Diagnostic report exported");
        EN.put("导出失败：", "Export failed: ");
        EN.put("无法打开文件管理器，请尝试下载到默认目录", "Cannot open the file manager; try downloading to the default folder");
        EN.put("无法打开日志，可在文件管理器的 Download/DeepSeekHarness 中查看，或重新下载", "Cannot open the log; check Download/DeepSeekHarness in a file manager, or download it again");
        EN.put("剪贴板不可用", "Clipboard unavailable");
        EN.put("DeepSeekHarness 诊断", "DeepSeekHarness diagnostics");
        EN.put("已复制脱敏报告", "Redacted report copied");
        EN.put("复制失败，可尝试导出报告", "Copy failed; you can export the report instead");
        EN.put("无法打开保存位置，请使用复制报告或检查系统文件管理器", "Cannot open the save location; use “Copy report” or check the system file manager");
        EN.put("正在检查环境…", "Checking the environment…");
        EN.put("报告保留在本机，复制或导出后可用于反馈", "The report stays on this device; copy or export it for feedback");
        EN.put("\n用户补充复现步骤：\n", "\nExtra reproduction steps by user:\n");
        EN.put("运行环境维护", "Runtime maintenance");
        EN.put("恢复原环境？", "Restore the previous environment?");
        EN.put("更新运行时？", "Update the runtime?");
        EN.put("备份并重建环境？", "Back up and rebuild the environment?");
        EN.put("先停止 Web，再回切旧环境，保留所有安全副本。", "Stops Web first, then switches back to the old environment; all safe backups are kept.");
        EN.put("会停止 Web 和终端任务，再更新 dsh 和内置插件，个人目录、会话和配置保持原位。验证失败回切原运行时。", "Stops Web and terminal tasks, then updates dsh and built-in plugins; personal folders, sessions and config stay in place. On verification failure it switches back to the original runtime.");
        EN.put("会停止 Web 并中断正在执行的任务，创建并校验安全备份后重建环境。备份失败不切换环境，后续失败回切旧环境。", "Stops Web and interrupts running tasks, then creates and verifies a safe backup before rebuilding. A failed backup keeps the environment; later failures switch back to the old one.");
        EN.put("继续", "Continue");
        EN.put("进入主界面", "Open main screen");
        EN.put("上次维护未完成，请先恢复原环境", "The last maintenance was not completed; restore the previous environment first");
        EN.put("环境维护", "Environment maintenance");
        EN.put("相同基础环境只更新 dsh 与内置插件，个人数据保持原位；基础环境变更时先保护数据再重建。验证失败可恢复原环境。", "With the same base environment only dsh & built-in plugins update and personal data stays in place; on base changes data is protected before rebuilding. On verification failure the previous environment can be restored.");
        EN.put("任务未完成。请按上方原因处理后重试；本页不会自动覆盖环境。", "Task incomplete. Address the reason above and retry; this page never overwrites the environment automatically.");
        EN.put("恢复中断维护", "Restore interrupted maintenance");
        EN.put("更新运行时", "Update runtime");
        EN.put("备份并重建环境", "Back up & rebuild environment");
        EN.put("请先恢复中断维护，再检查或修复环境", "Restore the interrupted maintenance before checking or repairing the environment");
        EN.put("无法开始安装任务，请稍后重试或先完成正在进行的环境任务", "Cannot start the install task; retry later or finish the running environment task first");
        EN.put("进行中", "In progress");
        EN.put("成功", "Success");
        EN.put("失败", "Failed");
        EN.put("未完成", "Incomplete");
        EN.put("未检查", "Not checked");
        EN.put("第 ", "Step ");
        EN.put(" 步 · ", " · ");
        EN.put("仅检查会显示实际运行结果；按需修复只处理检查失败的组件。", "Checking-only shows real run results; repair-on-demand fixes only the components that failed the check.");
        EN.put("按需修复", "Repair on demand");
        EN.put("重新检查", "Re-check");
        EN.put("环境任务进行中：", "Environment task in progress: ");
        EN.put("上次环境维护尚未完成，请先恢复原环境", "The last maintenance is incomplete; restore the previous environment first");
        EN.put("检查环境，或按需修复缺项", "Check the environment, or repair missing items on demand");
        EN.put("检查与按需修复", "Check & repair on demand");
        EN.put("仅检查", "Check only");
        EN.put(" · 总耗时 ", " · total ");
        EN.put(" · 当前阶段 ", " · current stage ");
        EN.put("\n正在取消检查…", "\nCancelling the check…");
        EN.put("\n等待当前修复到达安全点，随后停止", "\nWaiting for the repair to reach a safe point, then stopping");
        EN.put("，", ", ");
        EN.put("，点击查看详情", ", tap for details");
        EN.put("等待停止…", "Waiting to stop…");
        EN.put("取消检查", "Cancel check");
        EN.put("安全停止后续修复", "Safely stop further repairs");
        EN.put("执行后将在此逐行显示脱敏输出。", "Redacted output will appear here line by line after running.");
        EN.put("DeepSeek Harness 安装日志", "DeepSeek Harness install log");
        EN.put("已复制脱敏日志", "Redacted log copied");
        EN.put("复制失败，请稍后重试", "Copy failed; retry shortly");
        EN.put("已有环境任务进行中，请等待完成", "An environment task is running; wait for it to finish");
        EN.put("恢复中断维护？", "Restore interrupted maintenance?");
        EN.put("先停止 Web，再回切旧环境；安全备份和失败的新环境均保留。", "Stops Web first, then switches back to the old environment; safe backups and the failed new environment are kept.");
        EN.put("会停止 Web 并中断正在执行的任务，完整备份并校验配置、会话和本地插件，再重建环境并恢复数据。\n\n", "Stops Web and interrupts running tasks, fully backs up and verifies config, sessions and local plugins, then rebuilds the environment and restores data.\n\n");
        EN.put("备份失败不切换环境，后续失败回切旧环境；安全备份和旧环境会保留并占用额外空间。额外安装的系统软件留在旧环境中。", "A failed backup keeps the environment; later failures switch back to the old one. Safe backups and the old environment are kept and take extra space; extra system software stays in the old environment.");
        EN.put("恢复原环境", "Restore previous environment");
        EN.put("备份并重建", "Back up & rebuild");
        EN.put("已有环境任务或未完成维护，请稍后重试", "An environment task is running or maintenance is incomplete; retry later");
        EN.put("无法打开维护页，可到数据与备份页查看任务：", "Cannot open the maintenance page; check the task in Backup & Restore: ");
        EN.put("重启", "Restart");
        EN.put("安全启动 Web？", "Safe-start Web?");
        EN.put("停止当前启动，只加载官方基础界面。原插件开关、会话、模型和配置保留；普通重启后回到原配置。安全界面不加载移动插件等扩展。", "Stops the current start and loads only the official base UI. Plugin toggles, sessions, models and config are kept; a normal restart returns to the original config. The safe UI loads no mobile-plugin extensions.");
        EN.put("安全启动", "Safe start");
        EN.put("启动", "Start");
        EN.put("停止中…", "Stopping…");
        EN.put("启动中…（", "Starting… (");
        EN.put("）", ")");
        EN.put("先点「启动」，等鉴权链接就绪后再进入", "Tap “Start” first and enter once the auth link is ready");
        EN.put("正在验证 Web 访问权限…", "Verifying Web access…");
        EN.put("Web 鉴权失败，请点「进入」重试（", "Web authorization failed; tap “Open” to retry (");
        EN.put("Web 状态已变化，请等待就绪后重新进入", "Web state changed; wait until ready and enter again");
        EN.put("鉴权成功，正在打开 Web…", "Authorization OK, opening Web…");
        EN.put("无法打开 Web 页面，请重试（", "Cannot open the Web page; retry (");
        EN.put("无法开始 Web 鉴权，请重试", "Cannot start Web authorization; retry");
        EN.put("返回后可重新进入 Web", "You can re-enter Web after returning");
        EN.put("正在鉴权并打开 Web…", "Authorizing and opening Web…");
        EN.put("自动重启已暂停", "Auto-restart paused");
        EN.put("DSH 停止中…", "DSH stopping…");
        EN.put("DSH 启动中…", "DSH starting…");
        EN.put("基础界面已就绪 · 安全模式", "Base UI ready · safe mode");
        EN.put("DSH 已就绪，可进入", "DSH ready — open it");
        EN.put(" · 已兼容切换 proot", " · compatibility fallback to proot");
        EN.put("DSH 已停止", "DSH stopped");
        EN.put("DSH 未就绪", "DSH not ready");
        EN.put(" · 本阶段 ", " · this stage ");
        EN.put(" 秒 · 总计 ", " s · total ");
        EN.put(" 秒\n", " s\n");
        EN.put("下方实时显示启动输出；等待不会自动终止。", "Startup output streams below; waiting never ends it automatically.");
        EN.put("检测到插件或配置异常，可查看恢复选项。", "Plugin or config issues detected; check the recovery options.");
        EN.put("恢复选项", "Recovery options");
        EN.put("检测到 ", "Detected ");
        EN.put(" 项异常，查看插件与恢复选项", " issue(s); check plugin & recovery options");
        EN.put("失败 ", "Failed ");
        EN.put("/3，", "/3, ");
        EN.put("，查看恢复选项", ", check recovery options");
        EN.put("进入中…", "Opening…");
        EN.put("环境需要恢复", "Environment needs recovery");
        EN.put("查看环境维护与恢复选项", "View environment maintenance & recovery options");
        EN.put("正在获取本地访问地址中…", "Fetching local access address…");
        EN.put("本机访问地址：\n", "Local access address:\n");
        EN.put("本机地址", "Local address");
        EN.put("局域网地址（同 WiFi 的其它设备访问）：\n", "LAN address (for other devices on the same WiFi):\n");
        EN.put("局域网地址", "LAN address");
        EN.put("局域网已开启，但还没拿到 WiFi 地址（连上 WiFi 再看）", "LAN is on, but the WiFi address isn't available yet (check after joining WiFi)");
        EN.put("局域网代理正在等待本轮认证", "LAN proxy waiting for this round's authentication");
        EN.put("已复制：", "Copied: ");
        EN.put("复制失败：", "Copy failed: ");
        EN.put("未允许局域网访问；本机对话仍可使用，LAN / 无线 ADB 需在系统权限设置中开启", "Local-network access not allowed; on-device chat still works, but LAN / wireless ADB require enabling it in system permission settings");
        EN.put("当前黑夜模式，点击切换白天", "Dark mode on; tap to switch to light");
        EN.put("当前白天模式，点击切换黑夜", "Light mode on; tap to switch to dark");
        EN.put("发现新版本 ", "New version found: ");
        EN.put("查看更新", "View update");
        EN.put("中文", "Chinese");
        EN.put("侧边栏-", "Sidebar-");
        EN.put("省电模式", "Eco mode");
        EN.put("熄屏空闲 1 分钟后减少保活；有任务时继续运行。", "After 1 minute idle with screen off, reduces keep-alive; tasks keep running.");
        EN.put("持续保持运行，适合长时间任务。", "Stays running continuously; good for long tasks.");
        EN.put("界面语言 / Language", "Language");
        EN.put("DeepSeek Harness 手机端（DSHA 二开版）\n\n", "DeepSeek Harness for Android (DSHA fork)\n\n");
        EN.put("本软件完全免费开源，不收取任何费用，也没有会员、内购或任何付费功能。\n", "This software is completely free and open source — no fees, memberships, in-app purchases or any paid features.\n");
        EN.put("如果你是通过付费购买获得本软件，说明你被骗了，请立即退款，并到官方交流群反馈。\n\n", "If you paid to obtain this software, you were scammed — request a refund immediately and report it to the official community group.\n\n");
        EN.put("应用名称：DeepSeek Harness\n", "App name: DeepSeek Harness\n");
        EN.put("包名：", "Package: ");
        EN.put("版本：v", "Version: v");
        EN.put("开源地址：", "Open source: ");
        EN.put("交流QQ群：1125393952\n", "QQ group: 1125393952\n");
        EN.put("开发者QQ：3445790958", "Developer QQ: 3445790958");
        EN.put("关于 DeepSeek Harness", "About DeepSeek Harness");
        EN.put("打赏支持", "Donate");
        EN.put("加入交流群", "Join the group");
        EN.put("微信", "WeChat");
        EN.put("支付宝", "Alipay");
        EN.put("打赏支持（自愿）", "Donate (optional)");
        EN.put("开发者QQ", "Developer QQ");
        EN.put("无法打开链接", "Cannot open the link");
        EN.put("环境任务已结束；当前显示缓存列表，可点「刷新」同步插件状态", "Environment task finished; showing cached list — tap “Refresh” to sync plugin states");
        EN.put("未选择文件或文件管理器未返回文件。可点「其他文件选择器」重试，选择 ZIP / TAR.GZ 插件包。", "No file selected or the file manager returned nothing. Tap “Other file picker” to retry, choosing a ZIP / TAR.GZ plugin package.");
        EN.put("文件管理器返回的地址无法读取，请改用系统文件选择器。", "The address returned by the file manager cannot be read; use the system file picker instead.");
        EN.put("未获得文件读取权限，请改用系统文件选择器导入。", "No file-read permission; import with the system file picker instead.");
        EN.put("恢复第三方插件？", "Restore third-party plugins?");
        EN.put("恢复安全启动前已启用的插件；之后手动禁用的插件保持禁用。恢复后重启 Web 生效。", "Restores plugins that were enabled before the safe start; manually disabled ones stay disabled. Restart Web after restoring.");
        EN.put("恢复", "Restore");
        EN.put("使用提示", "Help");
        EN.put("支持通过链接、npm 包名安装插件，也支持 GitHub、npm 和 ZIP / TAR / TAR.GZ / TGZ 的已构建插件包；也可以粘贴 dsh 插件安装命令。安装或修改插件后，重启 Web 生效。导出包可在其他 DeepSeek Harness 中导入。", "Install plugins from links or npm package names, or built packages from GitHub, npm and ZIP / TAR / TAR.GZ / TGZ files; you can also paste a dsh plugin install command. Restart Web after installing or modifying plugins. Exported packages can be imported into another DeepSeek Harness.");
        EN.put("确认安装插件", "Confirm plugin install");
        EN.put("确认安装", "Confirm install");
        EN.put("请等待当前插件操作完成后再安装", "Wait for the current plugin operation to finish before installing");
        EN.put("dsh plugin --profile web add 插件包名", "dsh plugin --profile web add <package>");
        EN.put("插件链接或 npm 包名", "Plugin link or npm package name");
        EN.put("粘贴 dsh 插件安装命令，将自动提取包名安装。\n例如：dsh plugin --profile web add 插件包名", "Paste a dsh plugin install command; the package name is extracted automatically.\nExample: dsh plugin --profile web add <package>");
        EN.put("支持 GitHub 仓库、npm 包名、Release 下载链接和压缩包直链。", "Supports GitHub repos, npm package names, Release download links and direct archive links.");
        EN.put("命令", "Command");
        EN.put("地址", "Address");
        EN.put("粘贴", "Paste");
        EN.put("剪贴板没有内容", "Clipboard is empty");
        EN.put("已识别：", "Detected: ");
        EN.put("请输入内容", "Enter something first");
        EN.put("只看自己装的", "Only mine");
        EN.put("插件排序", "Sort plugins");
        EN.put("请等待当前插件操作完成后再导入", "Wait for the current plugin operation to finish before importing");
        EN.put("请选择插件压缩包；文件选择器无法返回时，可使用「其他文件选择器」。", "Choose a plugin archive; if the picker returns nothing, use “Other file picker”.");
        EN.put("未找到可用的文件选择器，请启用系统「文件」应用后重试。", "No usable file picker found; enable the system “Files” app and retry.");
        EN.put("没有可用的文件选择器", "No file picker available");
        EN.put("无法打开文件选择器，请使用备用入口：", "Cannot open the file picker; use the fallback entry: ");
        EN.put("正在处理插件", "Processing plugin");
        EN.put("插件操作结果", "Plugin operation result");
        EN.put("安装成功", "Install succeeded");
        EN.put("检测完成", "Check complete");
        EN.put("插件已删除", "Plugin deleted");
        EN.put("插件已回退", "Plugin rolled back");
        EN.put("插件已更新", "Plugin updated");
        EN.put("插件状态已更新", "Plugin state updated");
        EN.put("共 ", "Total ");
        EN.put(" 个插件", " plugins");
        EN.put("没有可导出的插件", "No plugins to export");
        EN.put("选择要导出的插件", "Choose plugins to export");
        EN.put("选择保存位置", "Choose save location");
        EN.put("请至少选择一个插件", "Select at least one plugin");
        EN.put("无法打开保存位置选择器", "Cannot open the save-location picker");
        EN.put("禁用官方核心？", "Disable the official core?");
        EN.put(" 是 Web 运行所需的核心，禁用后页面可能无法启动。", " is required for Web to run; disabling it may break the page.");
        EN.put("禁用", "Disable");
        EN.put("复制插件名称", "Copy plugin name");
        EN.put("复制来源链接", "Copy source link");
        EN.put("导出插件包", "Export plugin package");
        EN.put("检查插件更新", "Check plugin updates");
        EN.put("更新至 ", "Update to ");
        EN.put("回退至 ", "Roll back to ");
        EN.put("删除插件", "Delete plugin");
        EN.put("回退插件？", "Roll back plugin?");
        EN.put("\n只恢复插件文件，当前启用状态和对话数据保留；重启 Web 生效。", "\nOnly the plugin files are restored; enabled state and chat data are kept. Restart Web to apply.");
        EN.put("回退", "Roll back");
        EN.put("请等待当前插件操作完成", "Wait for the current plugin operation to finish");
        EN.put("删除插件？", "Delete plugin?");
        EN.put("将删除 ", "Will delete ");
        EN.put(" 的安装文件和启用记录。", "'s installed files and enabled record.");
        EN.put("\n对话、其他插件及外部源码目录会保留。需要留存时可先导出。", "\nChats, other plugins and external source folders are kept. Export it first if you need a copy.");
        EN.put("删除", "Delete");
        EN.put("已复制", "Copied");
        EN.put("临时插件 · 已运行", "Temporary plugin · running");
        EN.put("临时插件 · 未运行", "Temporary plugin · not running");
        EN.put("已启用", "Enabled");
        EN.put("已检测，可开启以加入 Web", "Detected; enable to join Web");
        EN.put("已禁用", "Disabled");
        EN.put("实体缺失，请重新导入", "Files missing; import again");
        EN.put("\n位置：", "\nLocation: ");
        EN.put("\n可更新：", "\nUpdate available: ");
        EN.put("\n上次检查版本：", "\nLast-checked version: ");
        EN.put("\n可回退：", "\nRollback available: ");
        EN.put("官方核心", "Official core");
        EN.put("DeepSeek Harness 内置插件", "Built-in DeepSeek Harness plugin");
        EN.put("第三方插件", "Third-party plugin");
        EN.put("更多操作：", "More actions: ");
        EN.put("禁用 ", "Disable ");
        EN.put("启用 ", "Enable ");
        EN.put("请在插件管理中查看 ", "Check the install & enable status of ");
        EN.put(" 的安装和启用状态", " in Manage plugins");
        EN.put("打开插件管理", "Open Manage plugins");
        EN.put("请先完成 DeepSeek Harness 首次初始化，完成后会返回插件安装确认页", "Finish the first-time DeepSeek Harness setup first; it will return to the plugin install confirmation page");
        EN.put("初始化 DeepSeek Harness", "Initialize DeepSeek Harness");
        EN.put("安装完成", "Installed");
        EN.put("下载并解析插件包后，会显示真实作者、版本和兼容范围。确认安装前不会启用插件。\n\n", "After the package is downloaded and parsed, the real author, version and compatibility range are shown. Plugins are not enabled before you confirm.\n\n");
        EN.put("解析链接 / 重试", "Parse link / Retry");
        EN.put("Web 尚未就绪，请返回启动页查看服务状态", "Web is not ready; return to the launch page to check the service status");
        EN.put("无法验证 Web 访问权限，请稍后重试", "Cannot verify Web access; retry shortly");
        EN.put("服务在鉴权期间重新启动，请稍后重试", "The service restarted during authorization; retry shortly");
        EN.put("终端尚未停止，保留会话与环境保护：", "Terminal not stopped; keeping the session and environment safe: ");
        EN.put("请在维护线程等待终端退出", "Wait for the terminal to exit on the maintenance thread");
        EN.put("环境未就绪 —— 先到「安装」页装完再回来", "Environment not ready — finish it on the Install page first");
        EN.put("正在维护环境，请完成后再启动终端", "Environment maintenance in progress; finish it before starting a terminal");
        EN.put("终端启动失败：", "Terminal start failed: ");
        EN.put("PTY 启动失败：", "PTY start failed: ");
        EN.put("暂无终端", "No terminal");
        EN.put("会话已结束", "Session ended");
        EN.put("关闭失败，会话仍保留：", "Close failed; session kept: ");
        EN.put("会话已结束，请点击「新建」", "Session ended; tap “New”");
        EN.put("已切到简易终端（PTY 会话仍在后台）", "Switched to Simple terminal (the PTY session keeps running in the background)");
        EN.put("请退出终端页再进来", "Leave the terminal page and come back");
        EN.put("会话已结束（退出码 ", "Session ended (exit code ");
        EN.put("已有数据任务进行中，可到数据与备份页查看。", "A data task is running; check the Backup & Restore page.");
        EN.put("备份并重建内置环境", "Back up & rebuild the built-in environment");
        EN.put("先停止 Web，再回切原环境；安全备份和失败的新环境均保留。", "Stops Web first, then switches back to the previous environment; safe backups and the failed new environment are kept.");
        EN.put("先停止 Web 并等待退出（会中断正在执行的任务），完整备份并校验配置、会话与本地插件，再解压并恢复。\n\n", "Stops Web and waits for exit (interrupts running tasks), fully backs up and verifies config, sessions and local plugins, then extracts and restores.\n\n");
        EN.put("备份失败不会切换环境；解压或恢复失败会回切。旧环境和安全备份留在私有目录，需要额外空间。\n", "A failed backup keeps the environment; a failed extract or restore switches back. The old environment and safe backups stay in the private folder and take extra space.\n");
        EN.put("原生配置和 API Key 保持原位；额外安装的系统软件留在旧环境中。", "Native config and API keys stay in place; extra system software stays in the old environment.");
        EN.put("算了", "Never mind");
        EN.put("已有任务或未完成维护，请到数据与备份页查看。", "A task is running or maintenance is incomplete; check the Backup & Restore page.");
        EN.put("打不开解压页：", "Cannot open the extract page: ");
        EN.put("自定义", "Custom");
        EN.put("npm 源", "npm source");
        EN.put("正在应用 npm 源…", "Applying npm source…");
        EN.put("npm 源已切换", "npm source switched");
        EN.put("Ubuntu 软件包源", "Ubuntu package source");
        EN.put("正在写入源并刷新索引…", "Writing the source and refreshing indexes…");
        EN.put("源已写入，但 apt-get update 有问题，可稍后在终端重试", "Source written, but apt-get update had issues; retry in the terminal later");
        EN.put("Ubuntu 软件包源已切换并刷新索引", "Ubuntu package source switched and indexes refreshed");
        EN.put("pip 源", "pip source");
        EN.put("正在应用 pip 源…", "Applying pip source…");
        EN.put("pip 源已切换", "pip source switched");
        EN.put("应用", "Apply ");
        EN.put("完成", "Done");
        EN.put("失败：", " failed: ");
        EN.put("请输入有效的源地址（http/https 开头）", "Enter a valid source URL (starting with http/https)");
        EN.put("未设置（默认）", "Not set (default)");
        EN.put("进入原因：", "Reason: ");
        EN.put("重试启动", "Retry start");
        EN.put("安全启动基础界面", "Safe-start base UI");
        EN.put("新建配置文件", "New config file");
        EN.put("恢复中断的配置修复", "Resume interrupted config repair");
        EN.put("恢复修复前配置", "Restore pre-repair config");
        EN.put("将使用修复前的快照回退中断的配置写入，然后才能重新启动。", "Rolls back the interrupted config write using the pre-repair snapshot; only then can you start again.");
        EN.put("环境安装与修复", "Environment install & repair");
        EN.put("查看并下载日志", "View & download logs");
        EN.put("刷新恢复记录", "Refresh recovery records");
        EN.put("\n\n操作会停止 Web 和终端，并保留修复前配置。", "\n\nThis stops Web and terminals and keeps the pre-repair config.");
        EN.put("已有任务进行中，请完成后重试。", "A task is running; finish it and retry.");
        EN.put("Web 启动配置", "Web startup config");
        EN.put("共享设置（settings.yaml）", "Shared settings (settings.yaml)");
        EN.put("共享补丁（cordis.patch.yml）", "Shared patch (cordis.patch.yml)");
        EN.put("选择新建的配置文件", "Choose the config file to create");
        EN.put("将以默认内容替换所选配置。原文件保存到修复前快照，插件文件、会话和原生 API Key 保留。", "Replaces the chosen config with default content. The original is saved to the pre-repair snapshot; plugin files, sessions and native API keys are kept.");
        EN.put("就绪", "Ready");
        EN.put("已停止", "Stopped");
        EN.put("启动中／已中断", "Starting / interrupted");
        EN.put("还没有启动记录。下一次启动会自动记录。", "No startup records yet. The next start will be recorded automatically.");
        EN.put("启动记录暂不可用：", "Startup records temporarily unavailable: ");
        EN.put("快照损坏，已禁止恢复：", "Snapshot corrupt; restore blocked: ");
        EN.put("健康启动", "Healthy start");
        EN.put("修复之前", "Before repair");
        EN.put("恢复所选配置快照", "Restore selected config snapshot");
        EN.put("\n只恢复这些配置文件；已卸载的插件不会自动重新安装。", "\nOnly these config files are restored; uninstalled plugins are not reinstalled automatically.");
        EN.put(" · 卸载", " · uninstall");
        EN.put("卸载插件", "Uninstall plugin");
        EN.put("\n仅卸载所选插件，使用现有插件管理器核验结果。", "\nUninstalls only the selected plugin; verify with the existing plugin manager.");
        EN.put("插件清单暂不可读；可先恢复或新建配置。\n", "Plugin list currently unreadable; restore or create a config first.\n");
        EN.put("配置修复未完成，请使用「恢复中断的配置修复」。", "Config repair incomplete; use “Resume interrupted config repair”.");
        EN.put("环境任务正在执行，完成后刷新即可。", "An environment task is running; refresh once it's done.");
        EN.put("配置文件使用软链接，已保留原文件。请手动检查链接目标。", "The config file uses a symlink; the original was kept. Check the link target manually.");
        EN.put("配置快照校验失败，未应用修复。", "Config snapshot verification failed; the repair was not applied.");
        EN.put("配置或快照已变化，请刷新后重新选择。", "Config or snapshot changed; refresh and choose again.");
        EN.put("配置文件超过快照大小限制或不是普通文件，原文件保留。", "The config file exceeds the snapshot size limit or is not a regular file; the original is kept.");
        EN.put("点击「新建」打开终端", "Tap “New” to open a terminal");
        EN.put("启动简易终端", "Start Simple terminal");
        EN.put("环境未就绪，请先到「安装」页完成安装", "Environment not ready; complete the install on the Install page first");
        EN.put("终端命令发送", "Sending terminal command");
        EN.put("终端命令发送失败", "Failed to send terminal command");
        EN.put("终端进程组无效", "Invalid terminal process group");
        EN.put("无法中止终端进程组", "Cannot stop the terminal process group");
        EN.put("旧终端启动器尚未退出", "The old terminal launcher has not exited");
        EN.put("已有环境任务启动，请稍后再打开终端", "An environment task is running; open the terminal later");
        EN.put("环境维护尚未完成，请先恢复维护，再打开终端", "Environment maintenance incomplete; restore it before opening a terminal");
        EN.put("上次环境维护未完成，请到安装与修复页恢复维护，再打开终端", "Last environment maintenance was incomplete; restore it on the Install & Repair page before opening a terminal");
        EN.put("正在执行环境任务", "Running an environment task");
        EN.put("，请稍后再打开终端或发送命令", "; open the terminal or send commands later");
        EN.put("命令未发送：请检查长度（最多 16K 字符）及空字符，输入已保留", "Command not sent: check the length (max 16K chars) and null chars; your input is kept");
        EN.put("中止中…", "Stopping…");
        EN.put("重试重启", "Retry restart");
        EN.put("中止并重启", "Stop & restart");
        EN.put("会话启动中，输入命令可排队", "Session starting; commands will queue");
        EN.put("命令执行中，新命令将排队", "Command running; new commands will queue");
        EN.put("中止并重启中，新命令将排队", "Stopping & restarting; new commands will queue");
        EN.put("会话已退出，输入命令自动启动", "Session exited; typing a command starts it");
        EN.put("会话失败，待发命令保留；点重试重启", "Session failed; pending commands are kept; tap to retry/restart");
        EN.put("输入命令，回车执行", "Type a command and press Enter");
        EN.put("暂无终端\n点击「新建」打开一个终端", "No terminal\nTap “New” to open one");
        EN.put("…（输出过长已截断）\n", "…(output truncated)\n");
        EN.put("请在维护任务线程等待终端退出", "Wait for the terminal to exit on the maintenance task thread");
        EN.put("未能确认简易终端已关闭；请勿移动或清除环境目录", "Could not confirm the Simple terminal closed; do not move or clear the environment directory");
        EN.put("×", "×");
        EN.put("关闭终端 ", "Close terminal ");
        EN.put("DeepSeek Harness 已更新到 ", "DeepSeek Harness updated to ");
        EN.put("，需要重启应用以完成更新。\n\n", "; restart the app to finish the update.\n\n");
        EN.put("更新完成", "Update complete");
        EN.put(" 秒后自动重启…", "s until auto-restart…");
        EN.put("立即重启", "Restart now");
        EN.put("稍后", "Later");
        EN.put("正在重启…", "Restarting…");
        EN.put("更新完成，等待重启应用", "Update complete; restart the app");
        EN.put("未检测到（环境未安装）", "Not detected (environment not installed)");
        EN.put("检查更新", "Updates");
        EN.put("更新到 ", "Update to ");
        EN.put("下载未启动", "Download not started");
        EN.put("网页已离开", "Page left");
        EN.put("网页文件消息无效", "Invalid page-file message");
        EN.put("网页文件传输失败", "Page-file transfer failed");
        EN.put("无法打开网页文件", "Cannot open the page file");
        EN.put("网页文件顺序错误", "Page-file sequence error");
        EN.put("网页已关闭", "Page closed");
        EN.put("网页文件不完整", "Page file incomplete");
        EN.put("网页文件读取失败", "Failed to read the page file");
        EN.put("未知网页文件消息", "Unknown page-file message");
        EN.put("网页文件传输超时", "Page-file transfer timed out");
        EN.put("网页文件未传完", "Page file not fully transferred");
        EN.put("下载完成，选择保存位置", "Download complete; choose a save location");
        EN.put("下载被系统中断，请重新导出", "Download interrupted by the system; export again");
        EN.put("此下载不是当前本机服务提供的文件", "This download is not a file from the current local service");
        EN.put("正在下载 ", "Downloading ");
        EN.put("无法创建下载缓存", "Cannot create the download cache");
        EN.put("下载跳转到了其他服务", "Download redirected to another service");
        EN.put("下载跳转地址缺失", "Download redirect address missing");
        EN.put("服务返回 HTTP ", "Service returned HTTP ");
        EN.put("存储空间不足", "Not enough storage space");
        EN.put("下载响应没有文件内容", "Download response has no file content");
        EN.put("已取消保存", "Save cancelled");
        EN.put("下载缓存已丢失，请重新导出", "Download cache lost; export again");
        EN.put("正在保存并校验文件", "Saving and verifying the file");
        EN.put("保存后无法读取校验", "Cannot read back for verification after saving");
        EN.put("保存校验失败，请更换位置重试", "Save verification failed; choose another location and retry");
        EN.put("已保存：", "Saved: ");
        EN.put("已取消", "Cancelled");
        EN.put("已取消下载或保存", "Download or save cancelled");
        EN.put("文件处理失败：", "File processing failed: ");
        EN.put("保存网页文件", "Saving web file");
        EN.put("无法打开保存位置选择器，请启用系统文件应用后重试", "Cannot open the save-location picker; enable the system Files app and retry");
        EN.put("文件尚未保存", "File not saved yet");
        EN.put("更换位置重试", "Choose another location and retry");
        EN.put("请先完成或取消当前文件下载", "Finish or cancel the current download first");
        EN.put("系统 WebView 版本未知", "System WebView version unknown");
        EN.put("拒绝非 content URI: ", "Rejected non-content URI: ");
        EN.put("上传成功 ", "Uploaded ");
        EN.put(" 个: ", " file(s): ");
        EN.put("复制失败: ", "Copy failed: ");
        EN.put("上传失败：", "Upload failed: ");
        EN.put("对话地址无效", "Invalid chat address");
        EN.put("请返回启动页，重新进入对话。", "Return to the launch page and enter the chat again.");
        EN.put("暂时无法进入对话", "Cannot enter the chat right now");
        EN.put("系统 WebView 无法启动", "System WebView failed to start");
        EN.put("请更新或启用 Android System WebView / Chrome，", "Update or enable Android System WebView / Chrome, ");
        EN.put("也可以使用系统浏览器进入对话。", "or use the system browser for the chat.");
        EN.put("系统 WebView 需要更新", "System WebView needs an update");
        EN.put("当前内核缺少：", "The current engine lacks: ");
        EN.put("。\n更新 Android System WebView / Chrome 后重试，或在浏览器中打开。", ".\nUpdate Android System WebView / Chrome and retry, or open it in a browser.");
        EN.put("暂时无法连接对话服务", "Cannot reach the chat service right now");
        EN.put("服务可能仍在启动或已退出。请稍后重试，", "The service may still be starting or has exited. Retry shortly, ");
        EN.put("持续失败时返回启动页查看日志。\n错误代码：", "and if it keeps failing, return to the launch page to check the log.\nError code: ");
        EN.put("对话认证已失效", "Chat authorization expired");
        EN.put("对话页面加载失败", "Chat page failed to load");
        EN.put("。请返回启动页重新进入对话，或稍后重试。", ". Return to the launch page to enter the chat again, or retry shortly.");
        EN.put("网页渲染进程已退出", "Page render process exited");
        EN.put("系统 WebView 发生异常，点击重试可重新打开；持续出现时请更新内核。", "System WebView hit an error; tap Retry to reopen. If it persists, update the engine.");
        EN.put("系统可能因内存不足回收了网页，点击重试可重新打开。", "The system may have reclaimed the page due to low memory; tap Retry to reopen.");
        EN.put("网页插件加载失败", "Web plugin failed to load");
        EN.put("\n返回启动页可查看插件详情，或安全启动进入基础界面。", "\nReturn to the launch page for plugin details, or safe-start into the base UI.");
        EN.put("无法打开文件选择器，请启用系统文件应用", "Cannot open the file picker; enable the system Files app");
        EN.put("未找到可用的系统浏览器", "No usable system browser found");
        EN.put("一次最多上传 20 个文件", "At most 20 files per upload");
        EN.put("无法创建上传缓存", "Cannot create the upload cache");
        EN.put("不支持的文件来源，请通过系统文件应用选择", "Unsupported file source; choose through the system Files app");
        EN.put("没有文件读取权限，请重新选择", "No file-read permission; choose again");
        EN.put("本次上传超过 256 MiB", "This upload exceeds 256 MiB");
        EN.put("无法读取文件，请检查授权后重新选择", "Cannot read the file; check permissions and choose again");
        EN.put("下一步", "Next");
        EN.put("需要存储权限", "Storage permission needed");
        EN.put("DeepSeek Harness 需要在容器中读写手机存储（如把工作区建到 /sdcard 任意位置）。", "DeepSeek Harness needs to read/write device storage inside the container (e.g. to place the workspace anywhere under /sdcard).");
        EN.put("请点击下方按钮在系统设置中开启「所有文件访问」权限，开启后返回本页再次点击「开始」。", "Tap the button below to enable “All files access” in system settings; after that, return here and tap “Start” again.");
        EN.put("跳过", "Skip");
        EN.put("保存备份设置", "Saving backup settings");
        EN.put("数据任务进行中，完成后再修改备份设置", "A data task is running; modify backup settings after it finishes");
        EN.put("备份设置保存失败，请重试", "Failed to save backup settings; retry");
        EN.put("备份保存在 Download/DeepSeekHarness/", "Backups are saved to Download/DeepSeekHarness/");
        EN.put("在 MT 管理器中添加本地存储，选择 DocumentsProvider → DeepSeek Harness。\n\n", "In MT Manager, add a local storage and choose DocumentsProvider → DeepSeek Harness.\n\n");
        EN.put("容器目录：files/linux/ubuntu/root\n", "Container folder: files/linux/ubuntu/root\n");
        EN.put("配置目录：容器中的 .dsh\n\n", "Config folder: .dsh inside the container\n\n");
        EN.put("找不到 DeepSeek Harness 时，先打开本 App 后重试。", "If DeepSeek Harness isn't listed, open this app first and retry.");
        EN.put("重置配置？", "Reset config?");
        EN.put("先停止 Web（会中断正在执行的任务）并创建校验安全备份，再重置 settings.yaml 和 .env；保留对话。", "Stops Web (interrupting running tasks) and creates a verified safe backup, then resets settings.yaml and .env; chats are kept.");
        EN.put("备份并重置", "Back up & reset");
        EN.put("停止 Web 后回切原环境；安全备份及失败的新环境都会保留。", "Stops Web and switches back to the old environment; safe backups and the failed new environment are kept.");
        EN.put("先停止 Web（会中断正在执行的任务），完整备份并校验配置、会话和本地插件，再重建环境并恢复数据。\n\n", "Stops Web (interrupting running tasks), fully backs up and verifies config, sessions and local plugins, then rebuilds the environment and restores data.\n\n");
        EN.put("旧环境和安全备份留在 App 私有目录，占用额外空间；任何失败均停止并尝试回切。额外安装的系统软件留在旧环境中。", "The old environment and safe backups stay in the app's private folder and take extra space; any failure stops and tries to switch back. Extra system software stays in the old environment.");
        EN.put("选择备份范围", "Choose backup scope");
        EN.put("即将备份：", "About to back up: ");
        EN.put("\n\n保存到 Download/DeepSeekHarness，每次使用独立文件名。", "\n\nSaved to Download/DeepSeekHarness with a unique filename each time.");
        EN.put("\n快照期间若数据变化，备份会失败，可在任务完成后重试。", "\nIf data changes during the snapshot, the backup fails; retry after the task completes.");
        EN.put("\n原生 API Key：", "\nNative API key: ");
        EN.put("按当前设置包含", "included per current settings");
        EN.put("按当前设置不包含", "not included per current settings");
        EN.put("\n配置文件和插件自身保存的凭据会随原文件一起备份。", "\nCredentials saved by config files and plugins are backed up with the original files.");
        EN.put("确认备份", "Confirm backup");
        EN.put("开始备份", "Start backup");
        EN.put("恢复备份", "Restore backup");
        EN.put("选择 .tar.gz 备份文件。预检会显示范围和版本，不停止 Web；确认恢复时才停止 Web，并中断正在执行的任务。", "Choose a .tar.gz backup file. Preflight shows the scope and version without stopping Web; Web stops (interrupting running tasks) only when you confirm the restore.");
        EN.put("选择文件", "Choose file");
        EN.put("打开选择器失败：", "Failed to open the picker: ");
        EN.put("请先点「恢复中断维护」，原环境尚未确认。", "Tap “Restore interrupted maintenance” first; the previous environment is not confirmed yet.");
        EN.put("已有数据任务进行中，请等待或处理恢复预览。", "A data task is running; wait for it or handle the restore preview.");
        EN.put("还没有成功备份", "No successful backup yet");
        EN.put("最近成功：", "Last success: ");
        EN.put("\n上次未完成：", "\nLast failure: ");
        EN.put("\n\n有未完成的环境维护，请恢复原环境后再继续。", "\n\nThere's incomplete environment maintenance; restore the previous environment before continuing.");
        EN.put("恢复预览", "Restore preview");
        EN.put("恢复此备份", "Restore this backup");
    }
    public static String status(String value) { return value; }
    public static String choose(String zh, String en) { return zh; }
}
